# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Install Flutter
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.2'


    # Accept Android SDK licenses
    - name: Accept Android SDK licenses
      run: yes | sdkmanager --licenses

    # Install dependencies
    - name: Install dependencies
      run: flutter pub get

    # Run tests
    # - name: Run tests
    #   run: flutter test

    # Build APK for Android
    - name: Build APK
      run: flutter build apk --release
